version: "3.9"

services:
    laravelapp:
        container_name: laravelapp
        image: razu/laravelapp:1.0.0
        build: .
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - db

    db:
        container_name: db
        image: postgres:12
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: gigalogytask
        volumes:
            - pgdata:/var/lib/postgresql/data

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        ports:
            - "5050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin
        depends_on:
            - db

    queue-worker:
        container_name: queue-worker
        image: razu/laravelapp:1.0.0
        build: .
        command: php artisan queue:work
        env_file:
            - .env
        depends_on:
            - db

volumes:
    pgdata: {}
